spring:
  application:
    name: onramp
  datasource:
    url: jdbc:mysql://localhost:3306/onramper
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          fusionauth:
            client-id: d1f69791-a04e-4e93-8460-7e2242844c53
            client-secret: No7z2JoKT6-0TAoYFZDGEuhNRDkjpWzdOBjtTjrzxZ0
            scope: openid, profile, email
            redirect-uri: http://localhost:8080/auth/callback
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          fusionauth:
            authorization-uri: http://localhost:9011/oauth2/authorize
            token-uri: http://localhost:9011/oauth2/token
            user-info-uri: http://localhost:9011/oauth2/userinfo
            jwk-set-uri: http://localhost:9011/.well-known/jwks.json
            user-name-attribute: sub