spring:
  application:
    name: onramp
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/onramper
    username: root
    password: your_root_password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          fusionauth:
            client-id: d1f69791-a04e-4e93-8460-7e2242844c53
            client-secret: No7z2JoKT6-0TAoYFZDGEuhNRDkjpWzdOBjtTjrzxZ0
            scope: openid, profile, email
            redirect-uri: http://localhost:8080/auth/callback
            authorization-grant-type: authorization_code
            client-authentication-method: post

        provider:
          fusionauth:
            authorization-uri: http://localhost:9011/oauth2/authorize
            token-uri: http://localhost:9011/oauth2/token
            user-info-uri: http://localhost:9011/oauth2/userinfo
            jwk-set-uri: http://localhost:9011/.well-known/jwks.json
            user-name-attribute: sub

  data:
    redis:
      host: localhost
      port: 6380
      password: your_secure_password


encryption:
  password: b684cc8de26de8ea4e363acc7d1e019622bf6d7795cd5e5d5ba33d147219cf2b
  salt: 6d2e87b80aa9e98edde68ac8944685bcba8880159be8b21660989878fbb2231e

auth:
  url: http://localhost:9011/oauth2/token
  client_id: d1f69791-a04e-4e93-8460-7e2242844c53
  client_secret: No7z2JoKT6-0TAoYFZDGEuhNRDkjpWzdOBjtTjrzxZ0
  grant_type: password
  scope: openid profile email

fusionauth:
  application_id: d1f69791-a04e-4e93-8460-7e2242844c53	  # Ensure this is a valid UUID
  passwordless:
    url: http://localhost:9011/api/passwordless/start
    login_url: http://localhost:9011/api/passwordless/login
  search_url: http://localhost:9011/api/user/search
  bearer_token: yJBgEtj9mCspXV1Ukk0uZd-K5s_vntr1fbGBtKmSfXZ_SMtEfqPf3P4x
  registration_url: http://localhost:9011/api/user/registration
  base-url: http://localhost:9011
  api-key: yJBgEtj9mCspXV1Ukk0uZd-K5s_vntr1fbGBtKmSfXZ_SMtEfqPf3P4x


nobitex:
  api:
    base-url: https://api.nobitex.ir/v2

logging:
  file:
    name: logs/onramp.log
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.onramp.controller: DEBUG
    com.onramp.service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.redis: DEBUG

elastic:
  apm:
    service_name: my-spring-app
    server_urls: http://localhost:8200
    environment: production
    application_packages: com.onramp


management:
  endpoint:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      elasticsearch:
        enabled: true
        host: http://localhost:9201  # Elasticsearch URL
        index: metrics-onramp  # Customize the index name
  elastic:
    metrics:
      export:
        enabled: true
        host: http://localhost:9201  # Elasticsearch URL
        index: metrics-onramp  # Customize the index name


spread:
  base: 2000

market:
  volatility:
    threshold: 0.05
  atr:
    threshold: 0.05
  rsi:
    overbought: 70
    oversold: 30

default:
  systemFee: 0.01
  transactionFee: 4.0
  redirectBaseUrl: https://www.amanatpay.com/redirect/booking/
  numberOfAllowedBookingDuplicates: 3